name: CI

on:
  push:
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  testApp:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Runs tests
      run: pytest
    - name: Create coverage report
      run: |
        pytest --cov=./
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true


  createContainer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build -t test .
    - name: Run
      run: docker run --name test -d -p 8080:8080 test
    - name: Get logs
      run: docker ps
    - name: Get logs
      run: docker logs test

  testContainer:
    needs: createContainer
    runs-on: ubuntu-latest
    steps:
    - name: Get logs
      run: docker ps
    - name: Test main route
      run: curl -o /dev/null -s -w "%{http_code}\n" localhost:8080
    - uses: nick-invision/assert-action@v1
      with:
        expected: 200
        actual: curl -o /dev/null -s -w "%{http_code}\n" localhost:8080